; Listing generated by Microsoft (R) Optimizing Compiler Version 19.31.31107.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__F32AA0BD_concurrencysal@h DB 01H
__5A3A63C4_sal@h DB 01H
__6BEC7B3D_vadefs@h DB 01H
__1BC54112_vcruntime@h DB 01H
__6569C2CA_corecrt@h DB 01H
__A2143F22_corecrt_stdio_config@h DB 01H
__829E1958_corecrt_wstdio@h DB 01H
__6DFAE8B8_stdio@h DB 01H
__309855C1_Source@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?ClearUsingIndex@@YAXQEAHH@Z			; ClearUsingIndex
PUBLIC	main
PUBLIC	__JustMyCode_Default
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ClearUsingIndex@@YAXQEAHH@Z DD imagerel $LN6
	DD	imagerel $LN6+121
	DD	imagerel $unwind$?ClearUsingIndex@@YAXQEAHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
_DATA	SEGMENT
?Array@@3PAHA DD 01H					; Array
	DD	02H
	DD	03H
	DD	04H
	DD	05H
	DD	06H
	DD	07H
	DD	08H
	DD	09H
	DD	0ffffffffH
_DATA	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025050f01H
	DD	010a230fH
	DD	070030021H
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ClearUsingIndex@@YAXQEAHH@Z DD 025051701H
	DD	01122317H
	DD	0700b0021H
	DD	0500aH
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT main
_TEXT	SEGMENT
size$ = 4
main	PROC						; COMDAT
; File C:\Users\Dell\OneDrive - The City College of New York\Desktop\Project2\Project2\Source.cpp
; Line 8
$LN3:
	push	rbp
	push	rdi
	sub	rsp, 264				; 00000108H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__309855C1_Source@cpp
	call	__CheckForDebuggerJustMyCode
; Line 9
	mov	DWORD PTR size$[rbp], 10
; Line 10
	mov	edx, DWORD PTR size$[rbp]
	lea	rcx, OFFSET FLAT:?Array@@3PAHA
	call	?ClearUsingIndex@@YAXQEAHH@Z		; ClearUsingIndex
; Line 11
	xor	eax, eax
	lea	rsp, QWORD PTR [rbp+232]
	pop	rdi
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?ClearUsingIndex@@YAXQEAHH@Z
_TEXT	SEGMENT
p$ = 8
array$ = 256
size$ = 264
?ClearUsingIndex@@YAXQEAHH@Z PROC			; ClearUsingIndex, COMDAT
; File C:\Users\Dell\OneDrive - The City College of New York\Desktop\Project2\Project2\Source.cpp
; Line 14
$LN6:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 264				; 00000108H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__309855C1_Source@cpp
	call	__CheckForDebuggerJustMyCode
; Line 16
	mov	eax, 4
	imul	rax, rax, 0
	mov	rcx, QWORD PTR array$[rbp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR p$[rbp], rax
	jmp	SHORT $LN4@ClearUsing
$LN2@ClearUsing:
	mov	rax, QWORD PTR p$[rbp]
	add	rax, 4
	mov	QWORD PTR p$[rbp], rax
$LN4@ClearUsing:
	movsxd	rax, DWORD PTR size$[rbp]
	mov	rcx, QWORD PTR array$[rbp]
	lea	rax, QWORD PTR [rcx+rax*4]
	cmp	QWORD PTR p$[rbp], rax
	jae	SHORT $LN3@ClearUsing
; Line 17
	mov	rax, QWORD PTR p$[rbp]
	mov	DWORD PTR [rax], 0
	jmp	SHORT $LN2@ClearUsing
$LN3@ClearUsing:
; Line 18
	lea	rsp, QWORD PTR [rbp+232]
	pop	rdi
	pop	rbp
	ret	0
?ClearUsingIndex@@YAXQEAHH@Z ENDP			; ClearUsingIndex
_TEXT	ENDS
END
